### ISSUE TITLE
Perfect! Needs Development For Second Monitor

### ISSUE THREAD

**Issue by sekmenhuseyin** [atagulalan/volumer#1]
First of all thank you very much for this wonderful app. It is really a time saver.
However I have double monitor and this app only works in my primary monitor

**Comment by atagulalan** [comment]
Thank you for the feedback, this should be fixed now.

Relevant Commit: [Added Multi-Monitor Support & Reduced Filesize](https://github.com/atagulalan/volumer/commit/33b441486908d858b2d22d302a49e98c89b2f643)
